#build angular application
FROM node:18-alpine AS builder 
WORKDIR /app
COPY package*.json ./
RUN npm install 
COPY . . 
RUN npm run build --prod
#serve with nginx
FROM nginx:alpine
COPY -- from=builder /app/dist/frontend /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
