server {
  listen 80;
  server_name locations;
  root /usr/share/nginx/html;
  index index.html
    
# This is critical for Angular routing
# Without this, refreshing any route gives 404
location / {
    try_files $uri $uri/ /index.html;
  }

# Cache static assests for performance
location ~* \.(js|css|png|jpg|gif|ico|svg) $ {
    exprires 1y;
    add_header Cache-Control "public, immutable";
  }
}
