version: '3.8' 
 
services: 
 
  # ===== SERVICE 1: MongoDB Database ===== 
  mongodb: 
    image: mongo:6.0 
    container_name: mongodb 
    restart: always 
    ports: 
      - "27017:27017" 
    volumes: 
      # This saves MongoDB data permanently even if container restarts 
      - mongo_data:/data/db 
    networks: 
      - mean_network
    # ===== SERVICE 2: Node.js Backend ===== 
  backend: 
    image: shivateja1100/mean-backend:latest 
    container_name: backend 
    restart: always 
    ports: 
      - "3000:3000" 
    environment: 
      # This connects backend to MongoDB using Docker service name 
      - MONGO_URI=mongodb://mongodb:27017/meandb 
      - PORT=3000 
      - NODE_ENV=production 
    depends_on: 
      - mongodb 
    networks: 
      - mean_network 
 
  # ===== SERVICE 3: Angular Frontend ===== 
  frontend: 
    image: shivateja1100/mean-frontend:latest 
    container_name: frontend 
    restart: always 
    depends_on: 
      - backend 
    networks: 
      - mean_network 
 
  # ===== SERVICE 4: Nginx Reverse Proxy ===== 
  nginx: 
    image: nginx:alpine 
    container_name: nginx_proxy 
    restart: always 
    ports: 
      # This is the ONLY port exposed to the internet 
      - "80:80" 
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro 
    depends_on: 
      - frontend 
      - backend 
    networks: 
      - mean_network 
 
# Persistent volume for MongoDB data 
volumes: 
  mongo_data: 
    driver: local 
 
# Internal network connecting all containers 
networks: 
  mean_network: 
    driver: bridge
