upstream frontend_app { 
    server frontend:80; 
} 
 
upstream backend_app { 
    server backend:3000; 
} 
 
server { 
    listen 80; 
    server_name _; 
   # Route /api/* requests to Node.js backend 
    location /api/ { 
        proxy_pass http://backend_app; 
        proxy_http_version 1.1; 
        proxy_set_header Upgrade $http_upgrade; 
        proxy_set_header Connection 'upgrade'; 
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_cache_bypass $http_upgrade; 
    } 
 
    # Route everything else to Angular frontend 
    location / { 
        proxy_pass http://frontend_app; 
        proxy_http_version 1.1; 
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    } 
} 
